### ISSUE TITLE
Not an issue, just seeking guidance

### ISSUE THREAD

**Issue by Rogerjwilkinson** [tjwei/xnes#19]
Trying to get this set up, and I must be an even bigger noob than I thought. Can somebody try to "dumb htis down" for me? I have emscripten SDK installed on my centos 6, along with what it said would be all relevant packages (python, nodejs, default-jre), I extract everything from the github, execute the ./buildall and

OUT=../../output
OBJECTS="../apu/apu.cpp ../apu/SNES_SPC.cpp ../apu/SNES_SPC_misc.cpp ../apu/SNES_SPC_state.cpp ../apu/SPC_DSP.cpp ../apu/SPC_Filter.cpp ../bsx.cpp ../c4.cpp ../c4emu.cpp  ../clip.cpp  ../controls.cpp ../cpu.cpp ../cpuexec.cpp ../cpuops.cpp ../dma.cpp ../dsp.cpp ../dsp1.cpp ../dsp2.cpp ../dsp3.cpp ../dsp4.cpp ../fxinst.cpp ../fxemu.cpp ../gfx.cpp ../globals.cpp  ../memmap.cpp  ../obc1.cpp ../ppu.cpp ../reader.cpp ../sa1.cpp ../sa1cpu.cpp  ../sdd1.cpp ../sdd1emu.cpp ../seta.cpp ../seta010.cpp ../seta011.cpp ../seta018.cpp  ../snes9x.cpp ../spc7110.cpp ../srtc.cpp ../tile.cpp sdlmain.cpp sdlinput.cpp sdlvideo.cpp sdlaudio.cpp"
INCLUDES="-I. -I.. -I../apu/"
CCFLAGS="-U__linux -O3 -DLSB_FIRST  -fomit-frame-pointer -fno-exceptions -fno-rtti -pedantic -Wall -W -Wno-unused-parameter -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -DHAVE_MKSTEMP -DHAVE_STRINGS_H -DHAVE_SYS_IOCTL_H -DHAVE_STDINT_H -DRIGHTSHIFT_IS_SAR -Wno-c++11-extensions"

emcc -O3 -s EXPORTED_FUNCTIONS="['_main', '_set_frameskip', '_set_transparency',  '_run',  '_toggle_display_framerate', '_S9xAutoSaveSRAM' ]" \
 -s FORCE_FILESYSTEM=1 \
 --shell-file xnes9x_shell.html \
 -o $OUT/snes9x.html \
 -DUSE_SDL \
 -DHTML $INCLUDES $CCFLAGS $OBJECTS \
 -lm -lSDL -s TOTAL_MEMORY=50331648  \
 -DSOUND
Traceback (most recent call last):
  File "/usr/bin/emsdk-portable/emscripten/1.37.28/emcc", line 9, in <module>
    if sys.version_info.major == 2:
AttributeError: 'tuple' object has no attribute 'major'

real    0m0.073s
user    0m0.030s
sys     0m0.026s

Stops there, and there's nothing in the output folder? I know this isn't really in the scope of what this section is for but I'm not realy sure where else to ask. Can somebody please point me in the direction I need to be? Would very much appreciate it. Thank you.

**Comment by tjwei** [comment]
Seems to be an emcc or python issue.
this statement  checks whether "sys.version_info.major" is 2 or not.
However, sys.version_info is a tuple according to the error message.
It is because the python installed ins not compatible with the emscripten.
Most likely the version of the python installed on your system is 2.6.
Install python 2.7 or python 3.6 can fix this problem.



Rogerjwilkinson <notifications@github.com>於 2018年1月28日 週日，下午5:25寫道：

**Comment by Rogerjwilkinson** [comment]
You were spot on mate, I underestimated how much I would have to put in to setting up a compiler environment (I'm a noob soz). Still working out some emscripten kinks and I'll report back when I get it going ^^

Thank you so much for replying!

**Comment by Rogerjwilkinson** [comment]
Okay, I'm back again. I think I got it this time? Maybe? I ran the buildall, and it placed

snes9x.html.mem

in the output folder, I think without issues? But I'm very confused, what, is a .mem file, what am I supposed to do with it? I thought this was supposed to output functional javascript? Thank you so much for putting up with me.

**Comment by tjwei** [comment]
I just tested it. There should be snes9x.html and snes0x.js in output folder as well.
