### ISSUE TITLE
Save state to localStorage?

### ISSUE THREAD

**Issue by krisives** [tjwei/xnes#5]

**Comment by tjwei** [comment]
Sounds like a reasonable feature request. I will add this feature and PR is also welcome.

**Comment by krisives** [comment]
Any idea how to do this? I don't know emscripten well but I am willing to do the legwork.

**Comment by krisives** [comment]
Reading the emscripten page on this:

http://kripken.github.io/emscripten-site/docs/porting/files/file_systems_overview.html#file-system-overview

From what I understand we can mount a file system that can be written to of various types, one being "IDBFS" which uses IndexedDB. I also found this tip:

> In combination with HTML 5 local storage (http://diveintohtml5.info/storage.html), it is possible to save the state of Emscripten’s virtual file system. To do so, the return values of FS.root and FS.nextInode should be saved, and then reassigned when the page is loaded in the future.

- Source https://cs-263-emscripten.readthedocs.org/en/latest/files.html

**Comment by tjwei** [comment]
Thanks, IDBFS seems to be the solution.

**Comment by jasmith79** [comment]
All of the saving functionality seems to be tied to an IFDEF named FANCY (as well as cheats and screenshots). But I can't find anywhere its defined, nor does it seem to be referenced in the original SNES9X code?
