### ISSUE TITLE
snes9x.js non-min file?

### ISSUE THREAD

**Issue by mgmedick** [tjwei/xnes#6]
Hi,

This isn't really an issue, but I thought others might have the same question so I opened an issue.

Is there a way we can get a non-min version of the snes9x.js file? When I run the buildall command using emscription I'm getting a minimized javascript file, if possible I would like the full version so I can better see where things blow up in the emulator, or the ability to tweak it.

**Comment by tjwei** [comment]
For now, you can modify  https://github.com/tjwei/xnes/blob/master/snes9x/sdl/buildhtml
and add the option -g1 to emcc, 
e.g. 
```sh
emcc -O3 -g1 -s EXPORTED_FUNCTIONS="['_main', '_set_frameskip', '_set_transparency',  '_run',  '_toggle_display_framerate' ]" \
 --closure 1  --shell-file xnes9x_shell.html \
 -o $OUT/snes9x.html -DUSE_SDL -DHTML $INCLUDES $CCFLAGS $OBJECTS -lm -lSDL -s TOTAL_MEMORY=34777216  -DSOUND 
```

Changing -O3 to -O2 or -O1 and setting --closure 0 might also help, but it is possible that you also need to increase TOTAL_MEMORY a bit.

**Comment by mgmedick** [comment]
Thanks so much this worked, I used the g1 argument, changed 03 to 01 and doubled the memory.

I found the meaning of the arguments here. https://kripken.github.io/emscripten-site/docs/tools_reference/emcc.html

**Comment by mgmedick** [comment]
Hey there, I just had a quick follow up question for you.

I noticed when I un-minned the snes9x.js file as descried above, the layout became more friendly but the functions and variables are still single characters. Is this just due to the fact that emscripten compiled the code? Is there no way to actually get meaningful function and variable names?

I would assume the answer is yes, but I saw a similar javascript emulator here (https://jquesnelle.github.io/mupen64plus-ui-console/) that also claims to be complied from emscripten and it has full function and variable names, so just wondering.

**Comment by tjwei** [comment]
The -g3 option should do the job.

**Comment by mgmedick** [comment]
Ok I understand now, should have read up on my emscripten before diving in. I used -g and -O0 to get the full code, i'll have to keep messing with it to get it right. I just wanted to make sure i wasn't stuck with this un-readable min-file. Now I understand that emscription can actually output the variable and function names. Thanks.

Arugments:
emcc -O0 -g -s ASSERTIONS=1 -s EXPORTED_FUNCTIONS="['_main', '_set_frameskip', '_set_transparency',  '_run',  '_toggle_display_framerate' ]" \
 --closure 0  --shell-file xnes9x_shell.html \
 -o $OUT/snes9x.html -DUSE_SDL -DHTML $INCLUDES $CCFLAGS $OBJECTS -lm -lSDL -s TOTAL_MEMORY=34777216 -DSOUND
